version: "3.1"
services:
  personal-website:
    image: personal-website-nginx
    container_name: personal-website-nginx-1
    ports:
      - "8080:80"
    build:
      context: ..
      dockerfile: docker/Dockerfile
