from nginx:1.17.9-alpine

COPY about.html /usr/share/nginx/html
COPY docs/ /usr/share/nginx/html/docs
COPY favicon.ico /usr/share/nginx/html
COPY images/ /usr/share/nginx/html/images
COPY index.html /usr/share/nginx/html
COPY style.css /usr/share/nginx/html
